# Site Settings
lang: en
icon: ğŸŸ
logo: https://avatars.githubusercontent.com/u/8283950
url: "https://megdna.github.io"
baseurl: "/mni"
permalink: :title
title: MnÃ­ WiÄhÃ³ni
description: Water Is Life

# Author Settings
author: Megan
email: meg@d8a.org
github: megdna
goatcounter: meg
mastodon: fediscience.org/@meg

nav:
  - name: About
    link: /about
  - name: Blog
    link: /blog
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap